# Generated by Django 3.0.5 on 2021-06-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=255)),
                ('FilePath', models.FilePathField(path='/home/suraj/Dev/trydjango/projects/adf_main/media')),
                ('Content_HTML', models.TextField()),
                ('Content_TEXT', models.TextField()),
                ('Page_no', models.IntegerField()),
            ],
        ),
    ]
